### PR TITLE
fix: Fix various ability bar bugs

### LINKED ISSUE #596: Custom Bars don't reset
### Version

1.12.1 (basically every other version as well)

### Brief Description

As the bossbar data (like focus, blood pool etc) are only updated when the bossbar is updated/sent, it does not reset to 0 when it should. Wynncraft fully removes your bossbar for Focus (and Awakened etc), but Wynntils doesn't recognize that it got removed, and the old data is kept

### Steps to Reproduce

Be on archer

Get the focus ability
Hit a shot with a bow

Miss a shot

### Expected Behaviour

Focus bar should be 0

### Actual Behaviour

Focus bar stays at 1

### Additional Comments

Im currently on a study trip. If anyone else wants to do this, feel free to. Otherwise, I would "fix" it once I'm back/have more time (at max in 3days)

### Installed Mods

_No response_

### PR DESCRIPTION
**Pull request by ryanzhoudev**
Fixes #596:
- Corrupted bar previously did not render properly
- Bars did not disappear when the vanilla Wynn one disappeared
- Bars did not differentiate between packet types

### CODE REVIEW

**Comment by ryanzhoudev** [comment]
Would be good if someone with sharpshooter could test in-game, I could only test for Blood Pool and Corrupted

File: src/main/java/com/wynntils/core/framework/instances/data/BossBarData.java [hunk 1]
```diff
@@ -14,67 +15,152 @@ public class BossBarData extends PlayerData {
...
         maxBloodPoolFormat.setRoundingMode(RoundingMode.DOWN);
     }
 
-    public void updateBossbarStats(SPacketUpdateBossInfo packet) {
-        // (!) Do not remove .getName() check, Intellij is wrong about it
-        if (packet == null || packet.getName() == null) return;
+    public void processAddPacket(SPacketUpdateBossInfo packet) {
+        String title = packet.getName().getFormattedText();
+        // This is a new bar being added, set the UUID field
+        // .contains checks are okay since the title is not a user input
```
Comment (Incompleteusern) [inline src/main/java/com/wynntils/core/framework/instances/data/BossBarData.java]: What if a guild contains one of the strings, unlikely as that is?

Comment (ryanzhoudev) [reply src/main/java/com/wynntils/core/framework/instances/data/BossBarData.java]: Oh that is true

**Review by Incompleteusern — DISMISSED** [review]
Looks good to me for the most part

**Review by Incompleteusern — APPROVED** [review]

File: src/main/java/com/wynntils/core/framework/instances/data/BossBarData.java [hunk 2]
```diff
@@ -14,67 +15,171 @@ public class BossBarData extends PlayerData {
...
+     * Clears the given bossbar's stats back to -1
+     * Also removes any related visible bars from the user
+     * @param packet the packet of the bossbar to clear
+     */
+    public void processRemovePacket(SPacketUpdateBossInfo packet) {
+        UUID uuid = packet.getUniqueId();
+
+        if (uuid.equals(BLOOD_POOL_UUID)) {
+            BLOOD_POOL_UUID = null;
+            get(CharacterData.class).setBloodPool(-1);
```
Comment (kristofbolyai) [inline src/main/java/com/wynntils/core/framework/instances/data/BossBarData.java:111]: In Artemis, I would say this will crash someone sometime, as we set an int which we essentially assume to be >=0 to be -1. But in legacy, this can work..

**Review by kristofbolyai — APPROVED** [review]
Looks okay
