### PR TITLE
Fix a crash related to chat rendering in `ChatOverlay`

### LINKED ISSUE #403: Chat Overlay Crash
### Version

CE1401

### Brief Description

Game crashed while joining a new world using /pfinder. Not really sure what caused it.

### Steps to Reproduce

Join some world via finding a /pfinder group.

### Crash Report

Time: 12/24/21 3:00 AM
Description: Unexpected error

java.lang.IndexOutOfBoundsException: Index: 8, Size: 8
	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
	at java.util.ArrayList.get(ArrayList.java:435)
	at com.wynntils.modules.chat.overlays.ChatOverlay.func_146230_a(ChatOverlay.java:78)
	at net.minecraftforge.client.GuiIngameForge.renderChat(GuiIngameForge.java:827)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:199)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1426)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

### Installed Mods

Wynntils, Phosphor, Optifine

### PR DESCRIPTION
**Pull request by kristofbolyai**
Fixes #403 (likely). Crash was likely caused because of the really unlikely event of `chatSize` getting outdated while running the for loop. Not "caching" the chat size will likely solve the issue.

### CODE REVIEW

File: src/main/java/com/wynntils/modules/chat/overlays/ChatOverlay.java [hunk 1]
```diff
@@ -74,7 +72,7 @@ public void drawChat(int updateCounter) {
             GlStateManager.scale(chatScale, chatScale, 1.0F);
             int l = 0;
 
-            for (int i1 = 0; i1 + scrollPos < chatSize && i1 < getLineCount(); ++i1) {
```
Comment (magicus) [inline src/main/java/com/wynntils/modules/chat/overlays/ChatOverlay.java:77]: If you believe there might be a race here, maybe you should extract getCurrentTab().getCurrentMessages() to a local variable, and operate on that? It will not help if the current message gets modified concurrently, but it will help against current tab replacing the current message. And since we don't really know what has triggered the bug, I think this feels more defensive.

**Review by magicus — APPROVED** [review]
LGTM now
