### PR TITLE
feat: Switch to discord-game-sdk4j and Activity Party bug fixes.

### LINKED ISSUE #486: Discord Game SDK crashes game on join
### Version

1.10.5

### Brief Description

Discord game SDK crashes when trying to set rich presence. Disabling rich presence fixes the crash.

This might be related to Minecraft's JNA.

### Steps to Reproduce

On affected installations, join Wynncraft with Rich presence on.

### Crash Report

https://hst.sh/yemurujope

### Installed Mods

Irrelevant

### PR DESCRIPTION
**Pull request by ghost**
Switch to [discord-game-sdk4j](https://github.com/JnCrMx/discord-game-sdk4j) to fix #486.

Fixes the pattern in [RPCJoinHandler.java L248](https://github.com/Wynntils/Wynntils/blob/1b4a9c0d60a5afd7cd255278fa4ae7fc3723efcf/src/main/java/com/wynntils/modules/richpresence/events/RPCJoinHandler.java#L148) (Now JoinHandler.java) not matching the actual GUI name. 
**This could be a beta change, can somebody with Hero/Champion double check that?**

Fixes [RPCJoinHandler.java L204-205](https://github.com/Wynntils/Wynntils/blob/1b4a9c0d60a5afd7cd255278fa4ae7fc3723efcf/src/main/java/com/wynntils/modules/richpresence/events/RPCJoinHandler.java#L204-L205) causing the Menu to infinitely reopen itself forcing the user to play on the World originally set in the secret for the whole session.

Fixes [RPCJoinHandler.java L71](https://github.com/Wynntils/Wynntils/blob/1b4a9c0d60a5afd7cd255278fa4ae7fc3723efcf/src/main/java/com/wynntils/modules/richpresence/events/RPCJoinHandler.java#L71) sending the msg without checking if the world is actually correct (Wynncrafts autojoin cause this).

### CODE REVIEW

**Comment by kristofbolyai** [comment]
Seems promising!

File: src/main/java/com/wynntils/modules/richpresence/events/ServerEvents.java [hunk 1]
```diff
@@ -72,16 +72,16 @@ public void onWarStageChange(WarStageEvent e) {
             currentTime = OffsetDateTime.now().plusSeconds(30);
             if (!RichPresenceConfig.INSTANCE.enableRichPresence) return;
             if (WarTimerOverlay.getTerritory() != null) {
-                RichPresenceModule.getModule().getRichPresence().updateRichPresenceEndDate("World " + (Reference.inStream ? "-" : Reference.getUserWorld().replace("WAR", "")), "Waiting for the war for " + WarTimerOverlay.getTerritory() + " to start", PlayerInfo.get(CharacterData.class).getCurrentClass().toString().toLowerCase(), getPlayerInfo(), currentTime);
+                RichPresenceModule.getModule().getCoreWrapper().updateRichPresenceEndDate("World " + (Reference.inStream ? "-" : Reference.getUserWorld().replace("WAR", "")), "Waiting for the war for " + WarTimerOverlay.getTerritory() + " to start", PlayerInfo.get(CharacterData.class).getCurrentClass().toString().toLowerCase(), getPlayerInfo(), currentTime);
```
Comment (ryanzhoudev) [inline src/main/java/com/wynntils/modules/richpresence/events/ServerEvents.java]: I don't think WAR worlds exist anymore; since we're already here, could you comb through this file and remove those?

Comment (ghost) [reply src/main/java/com/wynntils/modules/richpresence/events/ServerEvents.java]: I replaced `"World " + (Reference.inStream ? "-" : Reference.getUserWorld().replace("WAR", ""))` with the `getWorldDescription()` used in the non War cases.

But [Reference.java](https://github.com/Wynntils/Wynntils/blob/development/src/main/java/com/wynntils/Reference.java#L49) still checks for Worlds contaning WAR for its onWars check. 
ServerEvents, ClientEvents, NametagManager, WarManager and WarTimerOverlay all rely on this boolean. 

I am not part of a Guild or rich enough to create one so I can't really test other checks.

But changing it to true somewhere in here [WarTimerOverlay.java](https://github.com/Wynntils/Wynntils/blob/1b4a9c0d60a5afd7cd255278fa4ae7fc3723efcf/src/main/java/com/wynntils/modules/utilities/overlays/hud/WarTimerOverlay.java#L107-L116), and to false if the Stage get set to WAITING here [WarTimerOverlay.java](https://github.com/Wynntils/Wynntils/blob/1b4a9c0d60a5afd7cd255278fa4ae7fc3723efcf/src/main/java/com/wynntils/modules/utilities/overlays/hud/WarTimerOverlay.java#L228-L233) could work if all the other code still works.

**Review by ryanzhoudev — DISMISSED** [review]
Tried in-game, looks good. World numbers, usernames, classes, etc all like they're appearing okay

**Review by ryanzhoudev — APPROVED** [review]

**Review by Incompleteusern — APPROVED** [review]
